---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey
Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Knight High School i graduated in 2015. Math was easier than English for me but English was easy too. Math and Biology were and still are my best subjects.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a windows PC at home. I would rate myself a 8 out of 10. I know a great amount of PC stuff, mainly windows though, when it comes to Mac its more of a 6 out of 10. My internet connection works great almost all the time.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called by my name which is Alex. No nicknames or anything else, just straight up call me Alex.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to become a successful doctor one day. The college subject of greatest interest to me is Biology. I passes all my Bio classes with As and a few Bs. I am working on my bachelors in Sociology but at the same time working to get into the RN program here at AVC.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have only been to Mexico as a young kid way back in the day. I plan on traveling to Japan and Mexico in the future soon. Also Hawaii. I am not in the military and if i ever was drafted id prefer the Air Force. They seem as the most secure spot to me.  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
Currently this is Math 115. Taking this class to bring up my grade from my previous attempt at this class back at CSUN. I talked to my advisory and she recommended to retake this course to help me boost my grade to get more points for the RN program. The grade that i need to obtain is at least a B but I am aiming for an A.   
   
 






  




